version: "3"
services:
  app:
    build: .
    ports:
      - 8082:80
    volumes:
      - .:/var/www/html
    links:
      - mysql

  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 33061:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
